//vitals.ts
//color blind and eye testng

export const COLOR_BLIND_PLATES = [
    { id: 1, correct: '74', options: ['34', '45', '74'], image: '/img1.png' },
    { id: 2, correct: '45', options: ['48', '45', '15'], image: '/img2.png' },
    { id: 3, correct: '3',  options: ['8', '3', '5'],    image: '/img3.png' },
];


export type FieldType =
  | 'text'
  | 'email'
  | 'password'
  | 'tel'
  | 'number'
  | 'select'
  | 'multi-select'
  | 'file';

export const COMMON_SYMPTOMS = [
  "Other",
  "Fever",
  "Cough",
  "Headache",
  "Shortness of Breath",
  "Chest Pain",
  "Fatigue",
  "Body Ache",
  "Sore Throat",
  "Runny Nose",
  "Nausea",
  "Vomiting",
  "Diarrhea",
  "Dizziness",
  "High Blood Pressure",
  "Low Blood Pressure",
  "H/O fits",
  "Abnormal swelling in breast",
  "Allergies",
  "Anxiety",
  "Anxiety disorders in children",
  "Atopic eczema",
  "Attention deficit hyperactivity disorder (ADHD)",
  "Autistic spectrum disorder (ASD)",
  "Backache",
  "Backpain shifting to leg",
  "Bleeding from gums",
  "Bleeding while passing stools",
  "Blocked nose with pressure",
  "Bluish or red discoloration of fingers on exposure to cold",
  "Chest pain while coughing",
  "Chest pain with breathing",
  "Constipation",
  "Cough with sputum",
  "Cough with weightloss",
  "Cough-dry",
  "Cough-Productive",
  "Decreased appetite",
  "Decreased bleeding during periods",
  "Delayed periods",
  "Depression after childbirth",
  "Difficulty in breathing",
  "Earache",
  "Earwax build-up",
  "Excessive bleeding during periods",
  "Excessive snoring at night",
  "Febrile seizures",
  "Fever in adults",
  "Fever in children",
  "Fever with decreased blood pressure",
  "Fever with shivering Malaria/ viral infection",
  "Flu",
  "Food poisoning",
  "Frequent periods",
  "Gases in stomach",
  "Haemorrhoids (piles)",
  "Hard stools",
  "Head lice and nits",
  "Headache with vomiting and fever",
  "Hearing loss",
  "High cholesterol",
  "History of stones in gallbladder",
  "History of stones in kidneys",
  "Hyperglycaemia (high blood sugar)",
  "Hypoglycaemia (low blood sugar)",
  "Inability to conceive",
  "Inability to control stools",
  "Inability to fall asleep",
  "Inability to pass urine",
  "Inability to speak",
  "Incomplete urination",
  "Increased urge to move legs at night",
  "Increased appetite",
  "Increased sweating",
  "Indigestion",
  "Infections in finger nails",
  "Ingrown toe nail",
  "Inherited heart conditions",
  "Iron deficiency anaemia",
  "Irregular movements of body",
  "Irregular periods",
  "Itching",
  "Itching in skin folds",
  "Kidney infection",
  "Kidney stones",
  "Knee pain",
  "Leg cramps",
  "Loose motions",
  "Loose motions altering with constipation",
  "Loss of libido",
  "Loss of urinary control",
  "Lumps and bumps over the body",
  "Malnutrition",
  "Measles",
  "Migraine",
  "Milky discharge from breasts",
  "Miscarriage",
  "Mouth ulcer",
  "Nipples changes",
  "Nosebleed",
  "Numbness in hands and feet",
  "Pain Abdomen",
  "Pain in back",
  "Pain in breasts",
  "Pain in joints",
  "Pain in kidneys",
  "Pain in right lower abdomen",
  "Pain in small joints",
  "Pain in stomach",
  "Pain lower abdomen",
  "Pain Lumber region",
  "Pain right upper abdomen",
  "Pain while passing stools",
  "Pain while passing urine",
  "Painful contraction of muscle",
  "Pimples on face",
  "Pimples on face during periods",
  "Pimples with puss",
  "Pins and needles in hands and feet",
  "Pressure ulcers",
  "Psychosis",
  "Rash with sharp pain",
  "Reaction to medicine",
  "Recalls after traumatic incident",
  "Redness and swelling in breast",
  "Redness and swelling over the skin",
  "Restlessness in legs while sleeping",
  "Ringing in ears",
  "Severe pain in head and face",
  "Shortness of breath on exercise",
  "Shortness of breath on lying flat",
  "Shortness of breath on walking",
  "Shortness of breath(seasonal)",
  "Spinning of head",
  "Stomach abdominal pain",
  "Stomach ulcer",
  "Stress",
  "Sunburn",
  "Swelling on both sides of face",
  "Swellings on body",
  "Swellings over skin",
  "Toothache",
  "Tremors in fingers",
  "Tuberculosis (TB)",
  "Type 1 diabetes",
  "Type 2 diabetes",
  "Uncontrolled movements of limbs",
  "Urinary tract infection (UTI)",
  "Urinary tract infection (UTI) in children",
  "Urticaria (hives)",
  "Vaginal discharge",
  "Vaginal itching",
  "Vaginal thrush",
  "Vomiting in adults",
  "Vomitting",
  "Waking up from sleep due to shortness of breath",
  "Warts",
  "Weakness",
  "Weakness in lt/rt half of body",
  "Weight gain",
  "Weight loss",
  "Whooping cough",
  "Wrist pain",
  "Yellow discoloration in sclera",
  "Yellow discoloration of skin",
  "Abnormal sweating",
  "Aching joints",
  "Anemia",
  "Back pain",
  "Bedwetting",
  "Belching",
  "Blackheads",
  "Bleeding",
  "Blisters",
  "Blood in vomit",
  "Bloodshot eyes",
  "Blurred vision",
  "Boils",
  "Breast lumps",
  "Breast tenderness",
  "Breathlessness on exertion",
  "Breathlessness on lying flat",
  "Bruising",
  "Bulging veins",
  "Burning in hands",
  "Burning in mouth",
  "Burning sensation",
  "Chest tightness",
  "Chills",
  "Chronic cough",
  "Chronic fatigue",
  "Chronic muscle pain",
  "Clammy skin",
  "Clubbing of fingers",
  "Cold intolerance",
  "Confusion",
  "Conjunctivitis",
  "Cracked lips",
  "Cramping during exercise",
  "Cravings",
  "Cyanosis",
  "Dark circles under eyes",
  "Dark stools",
  "Darkened urine",
  "Decreased hearing",
  "Dehydration",
  "Delayed healing",
  "Depression",
  "Difficulty breathing when lying down",
  "Difficulty concentrating",
  "Difficulty in speaking",
  "Difficulty swallowing",
  "Difficulty waking up",
  "Discomfort when chewing",
  "Double vision",
  "Drowsiness",
  "Dry cough",
  "Dry eyes",
  "Dry mouth",
  "Dry skin",
  "Ear discharge",
  "Ear pain",
  "Easy bruising",
  "Easy crying",
  "Enlarged liver",
  "Enlarged lymph nodes",
  "Enlarged neck veins",
  "Enlarged spleen",
  "Enlarged thyroid",
  "Enlarged tonsils",
  "Enlarged veins",
  "Erectile dysfunction",
  "Excessive belching",
  "Excessive blinking",
  "Excessive salivation",
  "Excessive sleepiness",
  "Excessive thirst",
  "Eye discharge",
  "Eye floaters",
  "Eye pain",
  "Eyelid twitching",
  "Facial flushing",
  "Faint pulse",
  "Feeling hot and cold",
  "Feeling of fullness",
  "Fever blisters",
  "Fever sweats",
  "Flaking skin",
  "Floaters in vision",
  "Flushed skin",
  "Foot pain",
  "Frequent colds",
  "Frequent infections",
  "Fungal infections",
  "Goosebumps",
  "Grinding teeth",
  "Gum bleeding",
  "Gum swelling",
  "Hair loss",
  "Hair thinning",
  "Hand tremors",
  "Heartburn",
  "Heat intolerance",
  "Heavy feeling in legs",
  "Heavy menstrual bleeding",
  "Heel pain",
  "Hematemesis",
  "Hematuria",
  "Hemoptysis",
  "Hiccups",
  "Hives",
  "Hoarse voice",
  "Hoarseness",
  "Hot flashes",
  "Hyperpigmentation",
  "Hypersensitivity to light",
  "Hypopigmentation",
  "Inability to focus eyes",
  "Increased hair growth",
  "Increased reflexes",
  "Increased sensitivity to cold",
  "Increased thirst",
  "Increased urine output",
  "Insomnia",
  "Involuntary movements",
  "Irregular menstruation",
  "Irregular pulse",
  "Irritability",
  "Irritated eyes",
  "Itchy scalp",
  "Jaundice",
  "Joint pain",
  "Lightheadedness",
  "Lightheadedness on standing",
  "Lip sores",
  "Loss of appetite",
  "Loss of balance",
  "Loss of consciousness",
  "Loss of motor skills",
  "Loss of peripheral vision",
  "Loss of skin elasticity",
  "Loss of smell",
  "Loss of taste",
  "Menstrual cramps",
  "Metallic taste",
  "Mood swings",
  "Morning stiffness",
  "Mouth dryness",
  "Mouth ulcers",
  "Muscle aches",
  "Muscle pain",
  "Muscle tenderness",
  "Muscle tightness",
  "Muscle weakness",
  "Nail discoloration",
  "Nasal congestion",
  "Nasal itching",
  "Nasal polyps",
  "Neck cramps",
  "Neck stiffness",
  "Nerve pain",
  "Night blindness",
  "Nosebleeds",
  "Numb lips",
  "Numbness",
  "Oral thrush",
  "Pain behind eyes",
  "Pain in gums",
  "Pain in lower abdomen",
  "Pain in pelvis",
  "Pain in rib cage",
  "Painful breathing",
  "Painful gums",
  "Painful legs",
  "Painful lymph nodes",
  "Pale gums",
  "Pallor",
  "Palpitations",
  "Panic attacks",
  "Persistent cough",
  "Persistent yawning",
  "Poor wound healing",
  "Pounding heartbeat",
  "Pounding in head",
  "Prickling sensation",
  "Productive cough",
  "Protruding eyes",
  "Protruding jaw",
  "Raised red patches on skin",
  "Raised skin rash",
  "Rapid breathing",
  "Rapid heart rate",
  "Rashes around mouth",
  "Red eyes",
  "Red marks on skin",
  "Red spots on skin",
  "Red tongue",
  "Redness",
  "Reduced reflexes",
  "Restless legs",
  "Restlessness",
  "Scaling on lips",
  "Scalp itching",
  "Scaly skin patches",
  "Seizures",
  "Sensation of lump in throat",
  "Sensitive teeth",
  "Sensitivity to light",
  "Sensitivity to noise",
  "Sensitivity to smell",
  "Sensitivity to touch",
  "Shaking chills",
  "Shallow breathing",
  "Shivering",
  "Skin cracking",
  "Skin pallor",
  "Skin peeling",
  "Skin rash",
  "Sleep paralysis",
  "Slow breathing",
  "Slow heart rate",
  "Sneezing",
  "Sore tongue",
  "Sores on scalp",
  "Spider veins",
  "Sticky eyes",
  "Stinging sensation",
  "Stretch marks",
  "Sunken eyes",
  "Sweating",
  "Sweaty palms",
  "Swelling in joints",
  "Swelling of legs",
  "Swollen abdomen",
  "Swollen ankles",
  "Swollen eyelids",
  "Swollen face",
  "Swollen feet",
  "Swollen gums",
  "Swollen hands",
  "Swollen knuckles",
  "Swollen lymph nodes",
  "Swollen tongue",
  "Syncope",
  "Tearing",
  "Thickened skin",
  "Thickening of skin on palms",
  "Thirst",
  "Tight muscles",
  "Tingling cheeks",
  "Tingling fingers",
  "Tingling in extremities",
  "Tingling lips",
  "Tingling nose",
  "Tingling toes",
  "Tinnitus",
  "Tooth discoloration",
  "Tooth pain",
  "Trembling hands",
  "Tremors",
  "Tunnel vision",
  "Ulcers",
  "Unsteady gait",
  "Urinary retention",
  "Urinary urgency",
  "Vision changes",
  "Visual disturbances",
  "Visual snow",
  "Vomiting bile",
  "Water retention",
  "Weak pulse",
  "Weight fluctuation",
  "Wheezing",
  "White coating on tongue",
  "White patches in mouth",
  "White spots on nails",
  "White tongue",
  "Wobbly walking",
  "Low-grade",
  "Abdominal distension",
  "Abdominal pain",
  "Acid reflux",
  "Agitation",
  "Black, tarry stool",
  "Bloating",
  "Blood in stool",
  "Cloudy urine",
  "Decreased urine output",
  "Delirium",
  "Difficulty walking",
  "Disorientation",
  "Frequent urination",
  "Frequent yawning",
  "Gas",
  "Hallucinations",
  "Hip pain",
  "Leg pain",
  "Memory loss",
  "Muscle cramps",
  "Muscle stiffness",
  "Neck pain",
  "Night sweats",
  "Painful urination",
  "Paralysis",
  "Shoulder pain",
  "Slurred speech",
  "Speech difficulties",
  "Tender abdomen",
  "Tingling",
  "Twitching",
  "Urinary incontinence"
];